apiVersion: example.example.com/v1
kind: VisitorsApp
metadata:
  name: visitorsapp-sample
spec:
  # Default values copied from <project_dir>/helm-charts/visitors-helm/values.yaml
  backend:
    size: 1
  frontend:
    title: Helm Installed Visitors Site
  
  
